// Shared Phase 1 scope, used by both the Source of truth page and the Sprint board.

export const requirements = [
  {
    id: 'A', title: 'Access & environment', items: [
      ['A1', 'Dedicated WordPress admin account for Reemo'],
      ['A2', 'Staging copy of the WordPress site to build against'],
      ['A3', 'WordPress REST API enabled with an application password'],
      ['A4', 'WooCommerce REST API keys with read and write access'],
      ['A5', 'Hosting and deploy access, and a target domain for the webapp'],
      ['A6', 'LLM API key on Referee Abroad’s own account'],
      ['A7', 'Mailbox access for the inbox addresses'],
      ['A8', 'Brand assets and sample tournament data delivered'],
    ],
  },
  {
    id: 'B', title: 'Authentication', items: [
      ['B1', 'Referees log in with their existing WordPress credentials'],
      ['B2', 'The session persists across app restarts'],
      ['B3', 'Password reset uses the existing WordPress flow'],
      ['B4', 'A failed login shows a clear inline error'],
      ['B5', 'Logout clears the session'],
    ],
  },
  {
    id: 'C', title: 'WordPress & WooCommerce integration', items: [
      ['C1', 'Read tournaments from WooCommerce products'],
      ['C2', 'Read enrolments from WooCommerce orders'],
      ['C3', 'Create a WooCommerce order when a referee applies'],
      ['C4', 'Payment runs through the existing WooCommerce checkout'],
      ['C5', 'WordPress remains the single source of truth in Phase 1'],
      ['C6', 'Two-way sync keeps the app and WordPress in step'],
      ['C7', 'Webhooks notify the app of new and changed orders'],
      ['C8', 'Sync failures are retried automatically with backoff'],
      ['C9', 'Sync activity is logged for troubleshooting'],
    ],
  },
  {
    id: 'D', title: 'Referee webapp', items: [
      ['D1', 'Tournament list with name, dates and location'],
      ['D2', 'Tournament detail with description, dates and pitch info'],
      ['D3', 'Apply to a tournament from the detail screen'],
      ['D4', 'Pay for an application through the checkout'],
      ['D5', 'Documents screen lists the referee’s documents'],
      ['D6', 'Profile screen shows and edits personal details'],
      ['D7', 'In-app chat per tournament group'],
      ['D8', 'Direct message to the organisation'],
      ['D9', 'Unread badge on chat'],
      ['D10', 'Mobile-first layout for common phone sizes'],
      ['D11', 'A referee sees only their own match appointments, not other referees’ matches'],
      ['D12', 'Submit a match report (final score, fair play rating, notes)'],
      ['D13', 'Only the assigned main referee can open and submit the match report; server-enforced, assistants and visitors have no access'],
      ['D14', 'Tournament application status is clear per tournament: open, applied (awaiting), or confirmed (going)'],
      ['D15', 'Referees are appointed to matches directly (no accept or decline step)'],
    ],
  },
  {
    id: 'E', title: 'Tournament Command Centre', items: [
      ['E1', 'Tournament overview with status'],
      ['E2', 'Manage a tournament’s details'],
      ['E3', 'Enrolment list per tournament'],
      ['E4', 'Referee directory with profiles'],
      ['E5', 'Staff management'],
      ['E6', 'Broadcast a message to a tournament group'],
      ['E7', 'Support ticket inbox with a chat view'],
      ['E8', 'P&L overview per tournament'],
      ['E9', 'Analytics overview with totals and trends'],
      ['E10', 'Two-way sync status visible to admins'],
      ['E11', 'Left navigation across all sections'],
    ],
  },
  {
    id: 'I', title: 'Team & fixture import (CSV / Excel)', items: [
      ['I1', 'Import teams and fixtures from an uploaded file (CSV or Excel)'],
      ['I2', 'Accept any provider format and detect the header row automatically'],
      ['I3', 'Auto-map columns to fields (home, away, category, date, time, field, referees) with multilingual synonyms'],
      ['I4', 'Normalise age and gender from team names or a category field (e.g. u14girls, G18, birth year 2013)'],
      ['I5', 'Confirmation step to review and correct the mapping before import'],
      ['I6', 'Save a reusable mapping profile per organiser / source'],
      ['I7', 'Support fixtures that already include appointment columns (main, AR1, AR2, 4th)'],
      ['I8', 'Teams carry gender (boys, girls, mixed) alongside the age group'],
      ['I9', 'Recommended CSV template for organisers without an export system'],
    ],
  },
  {
    id: 'U', title: 'User interface & design build', items: [
      ['U1', 'Design system built in code: colours, typography and spacing tokens'],
      ['U2', 'Reusable component library: buttons, cards, inputs, chips, modals'],
      ['U3', 'Referee webapp screens built to the agreed design'],
      ['U4', 'Tournament Command Centre screens built to the agreed design'],
      ['U5', 'Loading states for every data view'],
      ['U6', 'Empty states with helpful copy'],
      ['U7', 'Error states with a retry option'],
      ['U8', 'Form validation with inline error styling'],
      ['U9', 'Consistent icon set and imagery'],
      ['U10', 'Micro-interactions and transitions (taps, hovers, sheets)'],
      ['U11', 'Responsive layouts across phone and desktop'],
      ['U12', 'Brand app icon and launch / splash screen'],
      ['U13', 'Visual QA and polish pass: spacing, alignment, consistency'],
    ],
  },
  {
    id: 'F', title: 'Referee appointing', items: [
      ['F1', 'Create matches per tournament (teams, time, pitch)'],
      ['F2', 'Appoint a referee to a match'],
      ['F3', 'Assign a role: main or assistant'],
      ['F4', 'Warn on double booking or time conflict'],
      ['F5', 'Push the appointment to the referee’s webapp'],
      ['F6', 'Referee sees the appointment in the app'],
      ['F7', 'Reassign or remove an appointment'],
    ],
  },
  {
    id: 'G', title: 'AI communication assistant', items: [
      ['G1', 'Chatbot embedded in the webapp'],
      ['G2', 'Chatbot answers grounded in the Referee Abroad FAQ'],
      ['G3', 'Chatbot signals when it is unsure instead of guessing'],
      ['G4', 'Unified inbox collects incoming mails'],
      ['G5', 'AI triages the topic'],
      ['G6', 'AI triages the urgency'],
      ['G7', 'AI tags the tournament'],
      ['G8', 'AI detects the language'],
      ['G9', 'AI drafts a reply from the FAQ and tournament data'],
      ['G10', 'Safe, high-confidence cases can be answered automatically'],
      ['G11', 'Low-confidence cases are drafted for human review'],
      ['G12', 'A human can edit and send any draft'],
      ['G13', 'Token usage is tracked for the monthly usage cost'],
      ['G14', 'No auto-answer on sensitive topics'],
    ],
  },
  {
    id: 'H', title: 'Notifications', items: [
      ['H1', 'Push notification on a new message'],
      ['H2', 'Push notification on a new appointment'],
      ['H3', 'In-app read status'],
    ],
  },
  {
    id: 'N', title: 'Non-functional', items: [
      ['N1', 'App loads within a reasonable time on mobile data'],
      ['N2', 'Sync retries with backoff on failure'],
      ['N3', 'Errors are logged and monitored'],
      ['N4', 'Personal data handled per GDPR; WordPress stays source in Phase 1'],
      ['N5', 'Data processing agreement in place where needed'],
      ['N6', 'Works on the latest iOS and Android browsers'],
      ['N7', 'Basic accessibility: contrast and tap targets'],
    ],
  },
  {
    id: 'Q', title: 'QA & launch', items: [
      ['Q1', 'QA across devices and browsers'],
      ['Q2', 'End-to-end test: apply, pay and order lands in WordPress'],
      ['Q3', 'End-to-end test: appointment, push and visible in the app'],
      ['Q4', 'Deployment to production'],
      ['Q5', 'Documentation and handover'],
      ['Q6', 'Two-week warranty window after go-live'],
    ],
  },
]

export const reqCount = requirements.reduce((a, g) => a + g.items.length, 0)
